## Linear Regression, Ridge and Lasso

In [1]:
#house pricing dataset
from sklearn.datasets import load_boston

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
df = load_boston()
df

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'}

In [13]:
# converting df into a DataFrame
dataset = pd.DataFrame(df.data)
dataset.columns = df.feature_names
dataset.head()
# these features (i.e CRIM, ZN,..., LSTAT) all are independent features

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [15]:
# Now, we will create the dependent feature (i.e Price)
dataset["Price"] = df.target

In [16]:
dataset.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [17]:
# Dividing the dataset into independent and dependent features
# X = independent freatures: column-0 to column-12
# Y = dependent freature: column-13
X = dataset.iloc[:,:-1]  # from all the columns skip the last column(i.e price)
Y = dataset.iloc[:,-1] # take the last column

In [18]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [19]:
Y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: Price, dtype: float64

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
# test_size = 0.33 means 33% data is used to test and the rest 77% to train the model

In [44]:
# Now, we will perform Linear Regression 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score  # cross validation makes different combinations of test data and training data

lin_reg = LinearRegression()  # import LinearRegression as lin_reg
mse = cross_val_score(lin_reg, X_train, Y_train, scoring='neg_mean_squared_error', cv=5)
print(mse)
mean_mse = np.mean(mse)
print(mean_mse)

[-33.75185215 -21.4641199  -27.97099777 -17.7140812  -25.03832267]
-25.187874739285096

In [60]:
# Fit the LinearRegression model
lin_reg.fit(X_train, Y_train)  # Training the model using independent (X) and dependent (Y) features

# Using the predict() function of the LinearRegression model
y_pred = lin_reg.predict(X_test)
print(y_pred)

[28.53469469 36.6187006  15.63751079 25.5014496  18.7096734  23.16471591
 17.31011035 14.07736367 23.01064388 20.54223482 24.91632351 18.41098052
 -6.52079687 21.83372604 19.14903064 26.0587322  20.30232625  5.74943567
 40.33137811 17.45791446 27.47486665 30.2170757  10.80555625 23.87721728
 17.99492211 16.02608791 23.268288   14.36825207 22.38116971 19.3092068
 22.17284576 25.05925441 25.13780726 18.46730198 16.60405712 17.46564046
 30.71367733 20.05106788 23.9897768  24.94322408 13.97945355 31.64706967
 42.48057206 17.70042814 26.92507869 17.15897719 13.68918087 26.14924245
 20.2782306  29.99003492 21.21260347 34.03649185 15.41837553 25.95781061
 39.13897274 22.96118424 18.80310558 33.07865362 24.74384155 12.83640958
 22.41963398 30.64804979 31.59567111 16.34088197 20.9504304  16.70145875
 20.23215646 26.1437865  31.12160889 11.89762768 20.45432404 27.48356359
 10.89034224 16.77707214 24.02593714  5.44691807 21.35152331 41.27267175
 18.13447647  9.8012101  21.24024342 13.02644969 21.80198374  9.48201752
 22.99183857 31.90465631 18.95594718 25.48515032 29.49687019 20.07282539
 25.5616062   5.59584382 20.18410904 15.08773299 14.34562117 20.85155407
 24.80149389 -0.19785401 13.57649004 15.64401679 22.03765773 24.70314482
 10.86409112 19.60231067 23.73429161 12.08082177 18.40997903 25.4366158
 20.76506636 24.68588237  7.4995836  18.93015665 21.70801764 27.14350579
 31.93765208 15.19483586 34.01357428 12.85763091 21.06646184 28.58470042
 15.77437534 24.77512495  3.64655689 23.91169589 25.82292925 23.03339677
 25.35158335 33.05655447 20.65930467 38.18917361 14.04714297 25.26034469
 17.6138723  20.60883766  9.8525544  21.06756951 22.20145587 32.2920276
 31.57638342 15.29265938 16.7100235  29.10550932 25.17762329 16.88159225
  6.32621877 26.70210263 23.3525851  17.24168182 13.22815696 39.49907507
 16.53528575 18.14635902 25.06620426 23.70640231 22.20167772 21.22272327
 16.89825921 23.15518273 28.69699805  6.65526482 23.98399958 17.21004545
 21.0574427  25.01734597 27.65461859 20.70205823 40.38214871]

In [64]:
from sklearn.metrics import r2_score
r2_score_linearReg = r2_score(Y_test, y_pred)  # Y_test are the read values and y_pred are the predicted values from linear regression
print(r2_score_linearReg)
# the value of r2_score_linearReg must be close to 1 (i.e 100%) for higher accuracy

0.7261570836552484

In [47]:
# Cross-Validation (mse and mean_mse): Helps you understand how well your linear regression model is likely to perform on unseen data and 
#detect potential overfitting or underfitting.For example, a lower mean MSE indicates better performance.

#The predict() function is used after the model is trained (using .fit()) to make predictions on new data.

In [51]:
# Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV # used for hyper-parameter tunning

ridge = Ridge()
params = {'alpha':[1e-15, 1e-10, 1e-8, 1e-3, 1e-2, 1, 5, 10, 20, 30, 35, 40, 45, 50, 55, 100]}
# we are taking so many alpha values because GridSearchCV will check all the values and give us the best value(i.e the value when model works the best)
ridge_regressor = GridSearchCV(ridge, params, scoring='neg_mean_squared_error', cv=10)
ridge_regressor.fit(X_train,Y_train)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 45, 50, 55, 100]},
             scoring='neg_mean_squared_error')

In [52]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 0.01}
-25.472067363367742

In [55]:
# -25.18 => Linear Regression & -25.47 => Ridge Regression
# When comparing NMSE values, a decrease means that the MSE is increasing
# Therefore, going from -25.18 to -25.47 means the MSE has increased from 25.18 to 25.47. 
# This indicates that the Ridge Regression model's predictions are bad than the Linear Regression model's predictions.
# Note: Our target is to go as close to 0 as possible

# Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV # used for hyper-parameter tunning

lasso = Lasso()
params = {'alpha':[1e-15, 1e-10, 1e-8, 1e-3, 1e-2, 1, 5, 10, 20, 30, 35, 40, 45, 50, 55, 100]}
# we are taking so many alpha values because GridSearchCV will check all the values and give us the best value(i.e the value when model works the best)
lasso_regressor = GridSearchCV(lasso, params, scoring='neg_mean_squared_error', cv=10)
lasso_regressor.fit(X_train,Y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2387.751964353788, tolerance: 2.7116020131147542
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3029.8788021507817, tolerance: 2.5569594885245905
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2858.404942828947, tolerance: 2.8039389377049178
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3009.7671406663276, tolerance: 2.677700852459017
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3177.870760536298, tolerance: 2.564250281967213
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3375.461939190316, tolerance: 2.583982937704918
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2503.671208021474, tolerance: 2.7500631278688528
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3460.8195858185513, tolerance: 2.7534481508196724
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3471.912316344309, tolerance: 2.762774118032787
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3033.602415186255, tolerance: 2.7204634411764705
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 45, 50, 55, 100]},
             scoring='neg_mean_squared_error')

In [56]:
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

{'alpha': 1e-08}
-25.473094572833237

In [62]:
# using predict() for Ridge
Y_pred = ridge_regressor.predict(X_test)
print(Y_pred)

[28.52859307 36.61391924 15.62446448 25.49794339 18.71651761 23.14663912
 17.30883131 14.07475692 22.99166445 20.54553336 24.90263157 18.40809393
 -6.52400321 21.82072889 19.14851303 26.0555678  20.29340873  5.74691746
 40.3292144  17.46378034 27.47957205 30.21416421 10.80664516 23.88716488
 18.00126984 16.01130598 23.25744349 14.37364861 22.3671398  19.31468367
 22.16363415 25.06329806 25.13823978 18.48393229 16.58826798 17.49443878
 30.7138197  20.06344919 23.98208654 24.9392659  13.98171769 31.64424572
 42.47600973 17.69471466 26.92334773 17.1620035  13.6905632  26.145616
 20.26656429 29.99670048 21.21064505 34.03300557 15.42093099 25.95970143
 39.14516313 22.95869281 18.81261673 33.07917693 24.74240933 12.83096178
 22.42715454 30.65664806 31.59958777 16.35222889 20.96015475 16.68403699
 20.23389533 26.14354346 31.12585147 11.90302348 20.45109263 27.46958133
 10.89755717 16.79681713 24.01250846  5.44645417 21.34784167 41.26752741
 18.13170091  9.78541651 21.23670746 13.00801021 21.80389016  9.48192028
 22.9891692  31.8989435  18.96346652 25.49171022 29.49086694 20.07366315
 25.56220367  5.59355694 20.18693075 15.09000395 14.35405658 20.85478081
 24.79424338 -0.21946712 13.5859797  15.62737036 22.03445812 24.69133724
 10.85151304 19.61436039 23.73582709 12.06813566 18.41749969 25.44869273
 20.78159819 24.69318085  7.50484425 18.91465693 21.72567149 27.14200965
 31.93243807 15.20142336 34.01094141 12.86221047 21.07368996 28.58334938
 15.77007631 24.78111478  3.65107257 23.90711146 25.82792884 23.03786781
 25.35874826 33.05326316 20.68744673 38.18127409 14.03406738 25.26164047
 17.6176464  20.59966964  9.87756487 21.05637121 22.21461852 32.29312098
 31.57395002 15.29657149 16.71588555 29.10259292 25.1703922  16.86494322
  6.32932136 26.68776841 23.37961384 17.25125102 13.22924135 39.49407945
 16.54176611 18.15737635 25.07169795 23.70262643 22.19971206 21.23926077
 16.88861638 23.17536326 28.70534889  6.66111129 23.98188285 17.21082949
 21.05931422 25.02120712 27.66542978 20.70837431 40.39262145]

In [63]:
from sklearn.metrics import r2_score
r2_score_ridge = r2_score(Y_test, Y_pred)  # Y_test are the real values and Y_pred are the predicted values of Ridge Regression
print(r2_score_ridge)
# the value of r2_score_ridge must be close to 1 (i.e 100%) for higher accuracy

0.7260978407192353